version: '3.8'

services:
  nginx-proxy:
    build:
      context: ./nginx-proxy
    image: ${REGISTRY_LOGIN_SERVER}/proposalgen-nginx:${IMAGE_TAG}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    image: ${REGISTRY_LOGIN_SERVER}/proposalgen-frontend:${IMAGE_TAG}
    restart: always
    environment:
      - VITE_BACKEND_URL=/api
    expose:
      - "80"
    depends_on:
      - backend

  backend:
    image: ${REGISTRY_LOGIN_SERVER}/proposalgen-backend:${IMAGE_TAG}
    restart: always
    environment:
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}  # Using Azure Redis Cache instead of container
      - REDIS_PASSWORD=${REDIS_PASSWORD}
