apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $_SERVICE_NAME
  namespace: $_PROJECT_ID
spec:
  template:
    spec:
      containers:
        - image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080   # Nginx listening port
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 4
            failureThreshold: 3
      timeoutSeconds: 300
      containerConcurrency: 80
  traffic:
    - latestRevision: true
      percent: 100
